import { useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, CreditCard, FileText, LayoutDashboard, LogOut, Plus, Search, Settings2, ShieldCheck, Users, Wallet, X } from 'lucide-react';
import { api, csrf, formData, money, type Allocation, type Member, type MemberProfile, type Overview, type Payment, type Session } from './api';

type Page='overview'|'members'|'payments'|'reports'|'manage'|'audit';
const names:Record<Page,string>={overview:'Overview',members:'Members',payments:'Payments',reports:'Reports',manage:'Manage',audit:'Audit history'};
const errorText=(e:unknown)=>e instanceof Error?e.message:'Please try again.';
const initials=(s:string)=>s.split(/\s+/).slice(0,2).map(x=>x[0]).join('');

function Alert({children}:{children:ReactNode}){return <div className="alert" role="alert"><CircleAlert size={17}/><span>{children}</span></div>;}
function Empty({children}:{children:ReactNode}){return <div className="empty"><FileText size={25}/><p>{children}</p></div>;}
function Badge({status}:{status:string}){return <span className={'badge '+status.toLowerCase().replaceAll(' ','-')}>{status}</span>;}
function Modal({title,subtitle,children,onClose,busy=false,wide=false}:{title:string;subtitle?:string;children:ReactNode;onClose:()=>void;busy?:boolean;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} className={wide?'wide':''} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="dialog-top"><div><span className="eyebrow">DUESDESK</span><h2>{title}</h2></div><button className="icon-button" aria-label="Close" disabled={busy} onClick={onClose}><X size={20}/></button></div>{subtitle&&<p className="dialog-subtitle">{subtitle}</p>}{children}</dialog>;
}

export default function App(){
 const [session,setSession]=useState<Session|null>(null),[page,setPage]=useState<Page>('overview'),[month,setMonth]=useState(''),[data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const [paymentOpen,setPaymentOpen]=useState(false),[editMember,setEditMember]=useState<Member|null|undefined>(undefined),[profile,setProfile]=useState<number|null>(null),[voiding,setVoiding]=useState<Payment|null>(null),[saved,setSaved]=useState<{id:number;receipt:string;amount:string}|null>(null),[toast,setToast]=useState('');
 const write=session?.role==='secretary';
 const changed=(message='Saved successfully.')=>{setRevision(x=>x+1);setToast(message);};
 useEffect(()=>{let alive=true;api<Session>('/api/session/').then(s=>{if(alive){setSession(s);setMonth(s.today.slice(0,7));}}).catch(e=>{if(alive){setError(errorText(e));setLoading(false);}});return()=>{alive=false;};},[]);
 useEffect(()=>{if(!month)return;let alive=true;setLoading(true);api<Overview>('/api/overview/?month='+month).then(d=>{if(alive){setData(d);setError('');}}).catch(e=>{if(alive)setError(errorText(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[month,revision]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
 const navigation:{page:Page;icon:typeof Users}[]=[{page:'overview',icon:LayoutDashboard},{page:'members',icon:Users},{page:'payments',icon:CreditCard},{page:'reports',icon:FileText},...(write?[{page:'manage' as Page,icon:Settings2}]:[]),...(session?.role!=='member'?[{page:'audit' as Page,icon:ShieldCheck}]:[])];
 const titles:Record<Page,[string,string]>={overview:['A clear view of your dues.','Track the month. Know who’s paid. Keep everything in order.'],members:['People behind the contributions.','Find a member, check their balance, or add someone new.'],payments:['Every payment, accounted for.','One receipt for every contribution, however many months it covers.'],reports:['Close the month with confidence.','Balances, collections and arrears, ready for your records.'],manage:['Your organisation, in order.','Manage accounts, import records and personalise receipts.'],audit:['A record you can follow.','Important changes, their reasons, and who made them.']};
 if(!session)return <div className="opening"><div className="logo-mark">d.</div><h1>Duesdesk</h1>{error?<><Alert>{error}</Alert><button onClick={()=>location.reload()}>Try again</button></>:<p>Opening your workspace…</p>}</div>;
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="logo-mark">d.</span>duesdesk<span>.</span></a><div className="workspace-label">MEMBERSHIP & FINANCE</div><nav aria-label="Main navigation">{navigation.map(({page:p,icon:Icon})=><button key={p} className={page===p?'nav active':'nav'} aria-current={page===p?'page':undefined} onClick={()=>{setPage(p);setError('');}}><Icon size={19}/>{names[p]}{page===p&&<ChevronRight size={15} className="nav-arrow"/>}</button>)}</nav><div className="dues-note"><span>MONTHLY CONTRIBUTION</span><strong>GH₵25 <small>/ member</small></strong><p>Every contribution accounted for.</p></div><div className="user-block"><span className="avatar">{initials(session.username)}</span><div><strong>{session.username}</strong><small>{session.role}</small></div><form action="/logout/" method="post"><input type="hidden" name="csrfmiddlewaretoken" value={csrf()}/><button className="signout" title="Sign out" aria-label="Sign out"><LogOut size={17}/></button></form></div></aside>
 <main className="main"><header className="topbar"><div>Workspace <span>/</span> <strong>{names[page]}</strong></div><div className="topbar-right"><span className="workspace-tag">{session.demo?'LOCAL TEST WORKSPACE':session.organisation}</span><a href="/account/password/" className="account-link">Change password</a></div></header><div className="content"><div className="page-heading"><div><span className="eyebrow">{session.role==='member'?'YOUR MEMBERSHIP STATEMENT':'MEMBERSHIP & CONTRIBUTIONS'}</span><h1>{titles[page][0]}</h1><p>{titles[page][1]}</p></div>{write&&<button className="button primary" onClick={()=>setPaymentOpen(true)}><Plus size={17}/>Record payment</button>}</div>
 {['overview','members','reports'].includes(page)&&<div className="period-bar"><label htmlFor="report-month">Reporting month <input id="report-month" type="month" value={month} min="2000-01" max="2100-12" onChange={e=>e.target.value&&setMonth(e.target.value)}/></label><span>All amounts in Ghana cedis (GH₵)</span></div>}
 {error&&<Alert>{error} <button className="text-button" onClick={()=>setRevision(x=>x+1)}>Retry</button></Alert>}
 {loading&&!data?<div className="loading" role="status">Loading your records…</div>:null}
 {data&&page==='overview'&&<><div className={'metrics '+(loading?'updating':'')}><Metric label="Money received this month" value={money(data.metrics.collections)} note="By the date payment was received" icon={<Wallet size={19}/>} accent/><Metric label="Outstanding this month" value={money(data.metrics.outstanding)} note="All billable members · selected month" icon={<Clock3 size={19}/>}/><Metric label="Fully paid members" value={`${data.metrics.paid} / ${data.metrics.active}`} note="Members billed for the selected month" icon={<CheckCircle2 size={19}/>}/><Metric label="Dues covered this month" value={money(data.metrics.assigned)} note="Includes payments received in advance" icon={<CreditCard size={19}/>}/></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><h2>Monthly payment status</h2><p>A quick check on this month’s contributions.</p></div><button className="text-button" onClick={()=>setPage('members')}>View members <ArrowUpRight size={14}/></button></div><StatusBar members={data.members}/><MemberTable members={data.members.filter(m=>m.status!=='Not due').slice(0,5)} compact onProfile={setProfile}/></section><section className="quick-guide"><span className="eyebrow">ONE PAYMENT. EVERY MONTH.</span><h2>GH₵100?<br/>Four months covered.</h2><p>Choose a member and a starting month. We’ll allocate the payment to monthly dues of GH₵25.</p><div className="month-example">{[1,2,3,4].map(n=><span key={n}>0{n}<strong>25</strong></span>)}</div><p className="small">Already-paid months are skipped. Part payments cover the remaining balance.</p>{write&&<button className="button dark" onClick={()=>setPaymentOpen(true)}>Try a payment <ArrowRight size={16}/></button>}</section></div><section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent payments</h2><p>One transaction, one receipt.</p></div><button className="text-button" onClick={()=>setPage('payments')}>All payments <ArrowUpRight size={14}/></button></div><PaymentTable items={data.recent} onVoid={write?setVoiding:undefined}/></section><div className="arrears-note"><span>Cumulative arrears through {formatMonth(month)}</span><strong>{money(data.metrics.arrears)}</strong><button className="text-button" onClick={()=>setPage('reports')}>See reports <ArrowRight size={14}/></button></div></>}
 {data&&page==='members'&&<Directory members={data.members} onProfile={setProfile} onAdd={write?()=>setEditMember(null):undefined}/>}
 {page==='payments'&&<PaymentLedger revision={revision} onVoid={write?setVoiding:undefined}/>}
 {data&&page==='reports'&&<Reports month={month} data={data}/>}
 {page==='manage'&&write&&<Manage session={session} members={data?.members||[]} onChange={changed}/>}
 {page==='audit'&&session.role!=='member'&&<AuditLog/>}
 <footer><strong>DUESDESK</strong><span>GH₵25 monthly dues · {session.demo?'Local test data':session.organisation}</span></footer></div></main>
 {paymentOpen&&<PaymentForm members={data?.members||[]} today={session.today} month={month} onClose={()=>setPaymentOpen(false)} onSaved={p=>{setPaymentOpen(false);setSaved(p);changed('Payment recorded.');}}/>}
 {editMember!==undefined&&<MemberForm member={editMember} today={session.today} onClose={()=>setEditMember(undefined)} onSaved={()=>{setEditMember(undefined);changed('Member saved.');}}/>}
 {profile!==null&&<Profile memberId={profile} canEdit={!!write} onClose={()=>setProfile(null)} onEdit={m=>{setProfile(null);setEditMember(m);}}/>}
 {voiding&&<VoidForm payment={voiding} onClose={()=>setVoiding(null)} onSaved={()=>{setVoiding(null);changed('Payment voided. Balances updated.');}}/>}
 {saved&&<Modal title="Payment recorded." onClose={()=>setSaved(null)}><div className="success-content"><span className="success-mark"><Check size={28}/></span><p>{money(saved.amount)} saved as <strong>{saved.receipt}</strong>.</p><a className="button primary" href={`/receipts/${saved.id}/`} target="_blank" rel="noopener noreferrer">View / print receipt <ArrowUpRight size={16}/></a><button className="button secondary" onClick={()=>setSaved(null)}>Done</button></div></Modal>}
 {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
 </div>;
}

function formatMonth(month:string){return month?new Date(month+'-01T12:00:00').toLocaleDateString('en-GH',{month:'long',year:'numeric'}):'';}
function Metric({label,value,note,icon,accent=false}:{label:string;value:string;note:string;icon:ReactNode;accent?:boolean}){return <article className={'metric '+(accent?'accent':'')}><div><span>{label}</span>{icon}</div><strong>{value}</strong><small>{note}</small></article>;}
function StatusBar({members}:{members:Member[]}){const due=members.filter(m=>m.status!=='Not due'),count=(s:string)=>due.filter(m=>m.status===s).length;return <div className="status-strip"><div className="status-bar"><span style={{width:`${due.length?count('Paid')/due.length*100:0}%`}}/><span style={{width:`${due.length?count('Partial')/due.length*100:0}%`}}/></div><div className="status-legend"><span><b>{count('Paid')}</b> paid</span><span><b>{count('Partial')}</b> partial</span><span><b>{count('Unpaid')}</b> unpaid</span></div></div>;}
function MemberTable({members,compact=false,onProfile}:{members:Member[];compact?:boolean;onProfile:(id:number)=>void}){return !members.length?<Empty>No matching members. Try a different filter or add a member.</Empty>:<div className="table-wrap"><table><thead><tr><th>Member</th>{!compact&&<><th>Phone</th><th>Membership</th></>}<th>Paid</th><th>Balance</th>{!compact&&<th>Cumulative arrears</th>}<th>Status</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><div className="member-cell"><span className="member-avatar">{initials(m.name)}</span><div><button className="member-name" onClick={()=>onProfile(m.id)}>{m.name}</button><small>{m.code}</small></div></div></td>{!compact&&<><td>{m.phone||'—'}</td><td>{m.member_status}</td></>}<td>{money(m.paid)}</td><td>{money(m.balance)}</td>{!compact&&<td>{money(m.arrears)}</td>}<td><Badge status={m.status}/></td></tr>)}</tbody></table></div>;}
function Directory({members,onProfile,onAdd}:{members:Member[];onProfile:(id:number)=>void;onAdd?:()=>void}){const [q,setQ]=useState(''),[status,setStatus]=useState('');const filtered=members.filter(m=>(!status||m.status===status)&&`${m.name} ${m.code} ${m.phone}`.toLowerCase().includes(q.toLowerCase()));return <section className="panel"><div className="panel-heading"><div><h2>Member directory <span className="count">{members.length}</span></h2><p>Choose a name to open the profile and payment history.</p></div>{onAdd&&<button className="button primary" onClick={onAdd}><Plus size={16}/>Add member</button>}</div><div className="filters"><div className="search-field"><Search size={17}/><input aria-label="Search members" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, member ID or phone"/></div><select aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All payment statuses</option>{['Paid','Partial','Unpaid','Not due'].map(s=><option key={s}>{s}</option>)}</select></div><MemberTable members={filtered} onProfile={onProfile}/></section>;}
function PaymentTable({items,onVoid}:{items:Payment[];onVoid?:(p:Payment)=>void}){return !items.length?<Empty>No payments recorded yet.</Empty>:<div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Member</th><th>Date received</th><th>Method</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{items.map(p=><tr key={p.id} className={p.voided?'voided':''}><td>{p.receipt} {p.voided&&<Badge status="Void"/>}</td><td>{p.member}</td><td>{p.date}</td><td>{p.method}</td><td><strong>{money(p.amount)}</strong></td><td><div className="row-actions"><a className="text-button" href={`/receipts/${p.id}/`} target="_blank" rel="noopener noreferrer">Receipt <ArrowUpRight size={13}/></a>{!p.voided&&onVoid&&<button className="text-button danger" onClick={()=>onVoid(p)}>Void</button>}</div></td></tr>)}</tbody></table></div>;}
function Pager({page,more,onChange}:{page:number;more:boolean;onChange:(n:number)=>void}){return <div className="pager"><button className="button secondary" disabled={page===1} onClick={()=>onChange(page-1)}><ArrowLeft size={14}/>Previous</button><span>Page {page}</span><button className="button secondary" disabled={!more} onClick={()=>onChange(page+1)}>Next<ArrowRight size={14}/></button></div>;}
function PaymentLedger({revision,onVoid}:{revision:number;onVoid?:(p:Payment)=>void}){const [page,setPage]=useState(1),[result,setResult]=useState<{payments:Payment[];has_more:boolean}|null>(null),[error,setError]=useState('');useEffect(()=>{let alive=true;setResult(null);api<{payments:Payment[];has_more:boolean}>('/api/payments/?page='+page).then(d=>{if(alive){setResult(d);setError('');}}).catch(e=>alive&&setError(errorText(e)));return()=>{alive=false;};},[page,revision]);return <section className="panel"><div className="panel-heading"><div><h2>Payment ledger</h2><p>All receipts, including advances and voided payments. 100 per page.</p></div></div>{error?<Alert>{error}</Alert>:result?<><PaymentTable items={result.payments} onVoid={onVoid}/><Pager page={page} more={result.has_more} onChange={setPage}/></>:<div className="loading">Loading payments…</div>}</section>;}

function MemberForm({member,today,onClose,onSaved}:{member:Member|null;today:string;onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await api(member?`/api/members/${member.id}/`:'/api/members/',formData(e.currentTarget));onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}return <Modal title={member?'Edit member':'Add a member'} onClose={onClose} busy={busy}><form onSubmit={submit}><label>Full name<input name="name" defaultValue={member?.name} maxLength={100} required/></label><div className="form-row"><label>Phone<input name="phone" type="tel" defaultValue={member?.phone} maxLength={30}/></label><label>Email<input name="email" type="email" defaultValue={member?.email}/></label></div><div className="form-row"><label>Date joined<input name="joined" type="date" defaultValue={member?.joined||today} min="2000-01-01" max={today} required/></label><label>Membership status<select name="status" defaultValue={member?.member_status||'Active'}>{['Active','Inactive','Suspended'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>Last billable month <span className="muted">(optional)</span><input type="month" name="billing_end" defaultValue={member?.billing_end}/></label><div className="info-note">Monthly dues are GH₵25. Leave the last billable month blank while membership continues. Status changes alone do not remove dues.</div>{error&&<Alert>{error}</Alert>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Saving…':'Save member'}</button></div></form></Modal>;}
function PaymentForm({members,today,month,onClose,onSaved}:{members:Member[];today:string;month:string;onClose:()=>void;onSaved:(p:{id:number;receipt:string;amount:string})=>void}){
 const [query,setQuery]=useState(''),[memberId,setMemberId]=useState(''),[amount,setAmount]=useState('100'),[start,setStart]=useState(month),[preview,setPreview]=useState<Allocation[]|null>(null),[previewError,setPreviewError]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[key]=useState(()=>crypto.randomUUID());
 const candidates=members.filter(m=>m.member_status==='Active'&&`${m.name} ${m.code}`.toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{let alive=true;setPreview(null);setPreviewError('');if(!memberId)return;const timer=setTimeout(()=>api<{allocations:Allocation[]}>('/api/payments/preview/',{member_id:memberId,amount,start_month:start}).then(d=>alive&&setPreview(d.allocations)).catch(e=>alive&&setPreviewError(errorText(e))),250);return()=>{alive=false;clearTimeout(timer);};},[memberId,amount,start]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const p=await api<{id:number;receipt:string;amount:string}>('/api/payments/',{...formData(e.currentTarget),member_id:memberId,amount,start_month:start,request_key:key});onSaved(p);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <Modal title="Record a payment" subtitle="One amount. A clear record of every month it covers." onClose={onClose} busy={busy}><form onSubmit={submit}><label>Find a member<input type="search" placeholder="Type a name or member ID" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Member<select value={memberId} onChange={e=>setMemberId(e.target.value)} required><option value="">Choose a member</option>{candidates.map(m=><option key={m.id} value={m.id}>{m.name} · {m.code}</option>)}{memberId&&!candidates.some(m=>String(m.id)===memberId)&&<option value={memberId}>{members.find(m=>String(m.id)===memberId)?.name}</option>}</select></label>{!members.some(m=>m.member_status==='Active')&&<Alert>Add an active member before recording a payment.</Alert>}<div className="form-row"><label>Amount (GH₵)<input type="number" min="0.01" max="3000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Start covering from<input type="month" value={start} onChange={e=>setStart(e.target.value)} required/></label></div><div className="form-row"><label>Date received<input name="payment_date" type="date" defaultValue={today} min="2000-01-01" max={today} required/></label><label>Payment method<select name="method">{['Cash','Mobile Money','Bank Transfer','Check'].map(m=><option key={m}>{m}</option>)}</select></label></div><label>Transaction reference <span className="muted">(optional)</span><input name="reference" maxLength={80} placeholder="e.g. Mobile Money transaction ID"/></label><label>Notes <span className="muted">(optional)</span><input name="notes" maxLength={500}/></label><div className="allocation-preview"><div className="preview-heading"><strong>Months covered</strong><span>GH₵25 / month</span></div>{preview?preview.map(a=><div key={a.month} className="allocation-row"><span>{a.month} <small>· {a.status}</small></span><strong>{money(a.amount)}</strong></div>):<p>{previewError||(!memberId?'Choose a member to preview the split.':'Calculating coverage…')}</p>}</div>{error&&<Alert>{error}</Alert>}<div className="dialog-actions"><button className="button secondary" type="button" onClick={onClose} disabled={busy}>Cancel</button><button className="button primary" disabled={busy||!preview}>{busy?'Saving…':'Save payment & receipt'}</button></div></form></Modal>;
}
function Profile({memberId,canEdit,onClose,onEdit}:{memberId:number;canEdit:boolean;onClose:()=>void;onEdit:(m:Member)=>void}){const [data,setData]=useState<MemberProfile|null>(null),[error,setError]=useState('');useEffect(()=>{let alive=true;api<MemberProfile>(`/api/members/${memberId}/`).then(d=>alive&&setData(d)).catch(e=>alive&&setError(errorText(e)));return()=>{alive=false;};},[memberId]);return <Modal title={data?.name||'Member profile'} onClose={onClose} wide>{error?<Alert>{error}</Alert>:data?<><div className="profile-meta"><p>{data.code} · {data.phone||'No phone added'}<br/>{data.email}</p>{canEdit&&<button className="button secondary" onClick={()=>onEdit(data)}>Edit member</button>}</div><div className="profile-metrics"><div><span>Total paid to date</span><strong>{money(data.total)}</strong></div><div><span>Arrears through this month</span><strong>{money(data.arrears)}</strong></div></div>{canEdit&&<div className="download-actions"><a className="button primary" href={`/api/members/${memberId}/report/`}><ArrowDownToLine size={16}/>Download payment report (Excel)</a></div>}<h3>Payment history</h3>{data.payments.length?data.payments.map(p=><div key={p.id} className="allocation-preview"><div className="preview-heading"><strong>{money(p.amount)} · {p.date}</strong><a href={`/receipts/${p.id}/`} target="_blank" rel="noopener noreferrer">{p.receipt} ↗</a></div><p>{p.method} {p.voided&&<Badge status="Void"/>}</p>{p.voided&&<p className="danger">{p.void_reason}</p>}{p.allocations.map(a=><div className="allocation-row" key={a.month}><span>{a.month}</span><span>{money(a.amount)}</span></div>)}</div>):<Empty>No payments yet.</Empty>}</>:<p>Loading member…</p>}</Modal>;}
function VoidForm({payment,onClose,onSaved}:{payment:Payment;onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{await api(`/api/payments/${payment.id}/void/`,formData(e.currentTarget));onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}return <Modal title={`Void ${payment.receipt}?`} onClose={onClose} busy={busy}><p>This {money(payment.amount)} payment for {payment.member} will stop counting towards balances. The original receipt and reason remain in the history. Record a replacement afterwards if needed.</p><form onSubmit={submit}><label>Reason for correction<textarea name="reason" minLength={5} maxLength={500} required/></label>{error&&<Alert>{error}</Alert>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="button danger-button" disabled={busy}>{busy?'Saving…':'Void payment'}</button></div></form></Modal>;}
function Reports({month,data}:{month:string;data:Overview}){const [kind,setKind]=useState('balances');const params=new URLSearchParams({month,kind});return <section className="panel report-card"><span className="eyebrow">MONTHLY REPORT</span><h2>Your month, ready to share.</h2><p>Download the {formatMonth(month)} report in Excel or CSV format.</p><label>Report type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="balances">Member balances and cumulative arrears</option><option value="payments">Payments received and voided receipts</option></select></label><div className="download-actions"><a className="button primary" href={'/export/excel/?'+params}><ArrowDownToLine size={16}/>Download Excel</a><a className="button secondary" href={'/export/?'+params}><ArrowDownToLine size={16}/>Download CSV</a></div><div className="report-total"><span>Cumulative arrears through {formatMonth(month)}</span><strong>{money(data.metrics.arrears)}</strong></div><div className="report-help"><h3>How the totals work</h3><p><b>Money received</b> counts valid payments by the date the money was received.</p><p><b>Dues covered</b> counts allocations to the selected month, including money received earlier.</p><p><b>Cumulative arrears</b> adds unpaid dues from joining through the selected month, capped at the last billable month. Future allocations do not settle earlier debt.</p><p>Voided payments stay in the payment report for traceability, marked VOID. They are excluded from valid collection totals.</p></div></section>;}

type Account={id:number;username:string;email:string;role:string;active:boolean};
type Organisation={name:string;contact:string;receipt_footer:string};
function Manage({session,members,onChange}:{session:Session;members:Member[];onChange:(s:string)=>void}){
 const [org,setOrg]=useState<Organisation|null>(null),[users,setUsers]=useState<Account[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[newAccount,setNewAccount]=useState(false),[disable,setDisable]=useState<Account|null>(null),[rev,setRev]=useState(0);
 useEffect(()=>{let alive=true;Promise.all([api<Organisation>('/api/settings/'),api<{users:Account[]}>('/api/accounts/')]).then(([o,u])=>{if(alive){setOrg(o);setUsers(u.users);setError('');}}).catch(e=>alive&&setError(errorText(e)));return()=>{alive=false;};},[rev]);
 async function saveOrg(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const o=await api<Organisation>('/api/settings/',formData(e.currentTarget));setOrg(o);onChange('Organisation details saved.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <>{error&&<Alert>{error}</Alert>}<div className="manage-grid"><section className="panel manage-card"><h2>Organisation & receipts</h2>{org?<form onSubmit={saveOrg}><label>Organisation name<input name="name" defaultValue={org.name} maxLength={120} required/></label><label>Contact details<input name="contact" defaultValue={org.contact} maxLength={200}/></label><label>Receipt message<input name="receipt_footer" defaultValue={org.receipt_footer} maxLength={250}/></label><p className="small">Monthly membership contribution: GH₵25.</p><button className="button primary" disabled={busy}>{busy?'Saving…':'Save details'}</button></form>:<p>Loading settings…</p>}</section><ImportCard onSaved={onChange}/></div><section className="panel"><div className="panel-heading"><div><h2>User accounts</h2><p>Secretaries manage records. Auditors read all records. Members see their own.</p></div><button className="button primary" onClick={()=>setNewAccount(true)}><Plus size={16}/>Add account</button></div><div className="table-wrap"><table><thead><tr><th>Username</th><th>Email</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.email||'—'}</td><td>{u.role}</td><td>{u.active?'Active':'Disabled'}</td><td>{u.active&&u.id!==session.user_id&&<button className="text-button danger" onClick={()=>setDisable(u)}>Disable access</button>}</td></tr>)}</tbody></table></div></section>{newAccount&&<AccountForm members={members} onClose={()=>setNewAccount(false)} onSaved={()=>{setNewAccount(false);setRev(x=>x+1);onChange('Account created. Share the initial password privately.');}}/>}{disable&&<DisableAccount user={disable} onClose={()=>setDisable(null)} onSaved={()=>{setDisable(null);setRev(x=>x+1);onChange('Account disabled.');}}/>}</>;
}
function AccountForm({members,onClose,onSaved}:{members:Member[];onClose:()=>void;onSaved:()=>void}){const [role,setRole]=useState('member'),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{await api('/api/accounts/',formData(e.currentTarget));onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}return <Modal title="Add a user account" onClose={onClose} busy={busy}><form onSubmit={submit}><label>Username<input name="username" maxLength={150} autoComplete="off" required/></label><label>Email<input type="email" name="email" required/></label><label>Initial password<input name="password" type="password" minLength={12} autoComplete="new-password" required/></label><p className="small">Use at least 12 characters. Share privately; the user can change it after signing in.</p><label>Access role<select name="role" value={role} onChange={e=>setRole(e.target.value)}><option value="member">Member — own records only</option><option value="auditor">Auditor — all records, read-only</option><option value="secretary">Secretary — manage records and accounts</option></select></label>{role==='member'&&<label>Linked member<select name="member_id" required><option value="">Choose a member</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.code}</option>)}</select></label>}{error&&<Alert>{error}</Alert>}<div className="dialog-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy?'Creating…':'Create account'}</button></div></form></Modal>;}
function DisableAccount({user,onClose,onSaved}:{user:Account;onClose:()=>void;onSaved:()=>void}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function disable(){setBusy(true);try{await api(`/api/accounts/${user.id}/disable/`,{});onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}return <Modal title={`Disable ${user.username}?`} onClose={onClose} busy={busy}><p>This user will lose access immediately. Their recorded payments and audit history remain.</p>{error&&<Alert>{error}</Alert>}<div className="dialog-actions"><button className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button danger-button" disabled={busy} onClick={disable}>{busy?'Disabling…':'Disable account'}</button></div></Modal>;}
function ImportCard({onSaved}:{onSaved:(s:string)=>void}){const [kind,setKind]=useState('members'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState<{token:string;count:number;preview:Record<string,string>[]}|null>(null);async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setPreview(null);try{const response=await fetch('/api/import/preview/',{method:'POST',credentials:'same-origin',headers:{'X-CSRFToken':csrf()},body:new FormData(e.currentTarget)});if(response.status===401){location.assign('/login/');return;}const result=await response.json();if(!response.ok)throw Error(result.error||'Could not read the file.');setPreview(result);}catch(e){setError(errorText(e));}finally{setBusy(false);}}async function commit(){if(!preview)return;setBusy(true);try{const r=await api<{count:number}>('/api/import/commit/',{token:preview.token});setPreview(null);onSaved(`${r.count} records imported.`);}catch(e){setError(errorText(e));}finally{setBusy(false);}}return <section className="panel manage-card"><h2>Import records</h2><p>Upload a CSV, review it, then confirm. Each file is imported completely or not at all.</p><form onSubmit={upload}><label>Import type<select name="kind" value={kind} onChange={e=>{setKind(e.target.value);setPreview(null);setError('');}}><option value="members">Members</option><option value="payments">Payments</option></select></label><p><a href={'/api/import/template/?kind='+kind}>Download CSV template <ArrowDownToLine size={13}/></a></p><label>CSV file<input type="file" name="file" accept=".csv,text/csv" onChange={()=>setPreview(null)} required/></label><p className="small">Up to 500 rows / 1 MB. Payments use the numeric member ID: 1 for MBR-0001. Allocations are recalculated when saved.</p><button className="button secondary" disabled={busy}>{busy?'Checking…':'Review import'}</button></form>{error&&<Alert>{error}</Alert>}{preview&&<div className="import-preview"><strong>{preview.count} rows ready · first {preview.preview.length} shown</strong><div className="table-wrap"><table><thead><tr>{Object.keys(preview.preview[0]).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{preview.preview.map((row,i)=><tr key={i}>{Object.entries(row).map(([k,v])=><td key={k}>{v||'—'}</td>)}</tr>)}</tbody></table></div><button className="button primary" disabled={busy} onClick={commit}>{busy?'Importing…':`Confirm ${preview.count}-row import`}</button></div>}</section>;}
type Audit={id:number;date:string;actor:string;action:string;entity:string;entity_id:string;details:unknown};
function AuditLog(){const [page,setPage]=useState(1),[result,setResult]=useState<{events:Audit[];has_more:boolean}|null>(null),[error,setError]=useState('');useEffect(()=>{let alive=true;setResult(null);api<{events:Audit[];has_more:boolean}>('/api/audit/?page='+page).then(d=>{if(alive){setResult(d);setError('');}}).catch(e=>alive&&setError(errorText(e)));return()=>{alive=false;};},[page]);return <section className="panel"><div className="panel-heading"><div><h2>Audit history</h2><p>Recorded changes cannot be edited or deleted through this app.</p></div></div>{error?<Alert>{error}</Alert>:!result?<div className="loading">Loading history…</div>:<>{result.events.length?result.events.map(e=><details className="audit-entry" key={e.id}><summary><strong>{e.action}</strong><span>{e.actor} · {new Date(e.date).toLocaleString('en-GH')}</span></summary><p>{e.entity} #{e.entity_id}</p><pre>{JSON.stringify(e.details,null,2)}</pre></details>):<Empty>No audit events recorded yet.</Empty>}<Pager page={page} more={result.has_more} onChange={setPage}/></>}</section>;}
