# Generated by Django 5.2.17 on 2026-09-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauthrejection',
            name='flow',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
