# Generated by Django 5.2.17 on 2026-09-30 15:44

import google_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0002_googleauthrejection_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('organization_name', models.CharField(max_length=120)),
                ('password_hash', models.CharField(max_length=256)),
                ('palette', models.JSONField(blank=True, default=dict)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('invite_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('token', models.CharField(db_index=True, default=google_auth.models.new_token, max_length=64)),
                ('code_hash', models.CharField(blank=True, default='', max_length=256)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('code_sends', models.JSONField(blank=True, default=list)),
                ('code_dead', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pending signup',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='googleauthrejection',
            name='method',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
