# Generated by Django 5.2.17 on 2026-10-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0003_pending_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
