# Generated by Django 5.2.17 on 2026-10-02 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_email_claims(apps, schema_editor):
    """Give every existing account an EmailClaim, or refuse to guess.

    ``EmailClaim.email`` is unique and stored lowercased. If two existing
    accounts already share an address case-insensitively, there is no honest way
    to choose which one owns the claim: silently dropping one would make the new
    uniqueness rule quietly untrue for that address. So the migration aborts and
    names every conflicting address, leaving the operator to resolve it. Nothing
    is invented and no row is deleted.

    Blank addresses are skipped: Django permits many accounts with ``email=''``
    and there is nothing to claim.
    """
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    EmailClaim = apps.get_model('google_auth', 'EmailClaim')
    alias = schema_editor.connection.alias

    owner = {}
    duplicates = set()
    for user_id, email in User.objects.using(alias).exclude(email='').values_list('pk', 'email').iterator():
        normalized = (email or '').strip().lower()
        if not normalized:
            continue
        if normalized in owner:
            duplicates.add(normalized)
        else:
            owner[normalized] = user_id

    if duplicates:
        raise RuntimeError(
            'EmailClaim backfill aborted: these addresses belong to more than one '
            'account (compared case-insensitively): ' + ', '.join(sorted(duplicates))
        )

    EmailClaim.objects.using(alias).bulk_create(
        [EmailClaim(email=email, user_id=user_id) for email, user_id in owner.items()]
    )


def remove_email_claims(apps, schema_editor):
    # Rolling back the table is the exact inverse: drop the rows this migration
    # created. No user is touched.
    EmailClaim = apps.get_model('google_auth', 'EmailClaim')
    EmailClaim.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('google_auth', '0006_record_legacy_identities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_claim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email claim',
            },
        ),
        migrations.CreateModel(
            name='SignupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('ip', models.CharField(blank=True, default='', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Signup attempt',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='PendingSignup',
        ),
        migrations.AddIndex(
            model_name='signupattempt',
            index=models.Index(fields=['email', '-created_at'], name='signup_attempt_email'),
        ),
        migrations.AddIndex(
            model_name='signupattempt',
            index=models.Index(fields=['ip', '-created_at'], name='signup_attempt_ip'),
        ),
        migrations.RunPython(backfill_email_claims, remove_email_claims),
    ]
