# Generated by Django 5.2.17 on 2026-09-25 13:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_assign_missing_user_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='duesmonth',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='accent',
            field=models.CharField(default='#527735', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name='organisation',
            name='primary',
            field=models.CharField(default='#214f43', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='organisation',
            name='public_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='secondary',
            field=models.CharField(default='#edf4e6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AlterField(
            model_name='duesmonth',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='digest',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='duesmonth',
            constraint=models.UniqueConstraint(fields=('organization', 'month'), name='org_dues_month'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'digest'), name='org_import_digest'),
        ),
        migrations.AddField(
            model_name='secretaryinvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretaryinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.AddField(
            model_name='secretaryinvite',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
