# Generated by Django 5.2.17 on 2026-09-29 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# The audit vocabulary used two spellings for the same idea. Normalise the rows
# already recorded so history reads consistently with what is written from now
# on. These are pure renames: no event changes meaning, only its name.
LEGACY_ACTION_RENAMES = {
    'organisation.updated': 'organization.updated',
    'report.exported': 'export.generated',
    'member.report_exported': 'member.export.generated',
}


def normalise_action_names(apps, schema_editor):
    AuditEvent = apps.get_model('ledger', 'AuditEvent')
    alias = schema_editor.connection.alias
    for old, new in LEGACY_ACTION_RENAMES.items():
        # Bulk update: the instance guard that makes audit rows append-only is
        # deliberately not in force for a historical model, and a data migration
        # is exactly the one legitimate time to rewrite them.
        AuditEvent.objects.using(alias).filter(action=old).update(action=new)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_secretary_only_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='http_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='outcome',
            field=models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('denied', 'denied'), ('rejected', 'rejected'), ('replayed', 'replayed')], default='success', max_length=10),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='reason',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='entity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='entity_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.organisation'),
        ),
        migrations.RunPython(normalise_action_names, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', '-created_at'], name='audit_org_created'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-created_at'], name='audit_action_created'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='audit_request_id'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['entity', 'entity_id', '-created_at'], name='audit_resource_created'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor', '-created_at'], name='audit_actor_created'),
        ),
    ]
