# Generated by Django 5.2.17 on 2026-10-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auditevent_http_method_auditevent_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='onboarding_required',
            field=models.BooleanField(default=False),
        ),
    ]
